(() => {
  "use strict";
  const form=document.querySelector("#global-search-form"),input=document.querySelector("#global-search"),results=document.querySelector("#search-results"),status=document.querySelector("#search-status");let entries=[];
  const normalize=value=>value.toLocaleLowerCase("pt-BR").normalize("NFD").replace(/[\u0300-\u036f]/g,"").trim().replace(/\s+/g," ");
  const near=(left,right)=>{if(Math.abs(left.length-right.length)>1)return false;let previous=[...Array(right.length+1).keys()];for(let i=1;i<=left.length;i++){const current=[i];for(let j=1;j<=right.length;j++)current[j]=Math.min(current[j-1]+1,previous[j]+1,previous[j-1]+(left[i-1]===right[j-1]?0:1));previous=current;}return previous[right.length]<=1;};
  const matches=(entry,query)=>{const words=entry.searchText.split(" ");return normalize(query).split(" ").every(term=>entry.searchText.includes(term)||words.some(word=>near(word,term)));};
  const label={map:"Ver no mapa",atlas:"Abrir no atlas",scene3d:"Explorar em 3D"},knowledge={known:"Conhecido",unknown:"Desconhecido",legendary:"Lendário"};
  const render=()=>{const query=input.value.trim();results.replaceChildren();if(!query){status.textContent=`${entries.length} itens públicos indexados. Digite um nome ou tema.`;return;}const found=entries.filter(entry=>matches(entry,query)).slice(0,30);for(const item of found){const article=document.createElement("article");article.className="panel search-card";const title=document.createElement("h2");title.textContent=item.title;const meta=document.createElement("p");meta.className="search-meta";for(const value of [knowledge[item.knowledge],...item.themes]){const badge=document.createElement("span");badge.textContent=value;meta.append(badge);}const links=document.createElement("p");links.className="search-destinations";for(const [scale,url] of Object.entries(item.destinations)){const link=document.createElement("a");link.href=url;link.textContent=label[scale];links.append(link);}article.append(title,meta,links);results.append(article);}if(!found.length){const empty=document.createElement("section");empty.className="panel search-empty";empty.innerHTML="<h2>Nenhum resultado</h2><p>Tente um nome mais curto, outra grafia ou consulte o atlas.</p>";results.append(empty);}status.textContent=found.length?`${found.length} resultado(s) encontrado(s).`:`Nenhum resultado para ${query}.`;history.replaceState(null,"",`#q=${encodeURIComponent(query)}`);};
  form.addEventListener("submit",event=>{event.preventDefault();render();results.querySelector("a")?.focus();});input.addEventListener("input",()=>{if(!input.value)render();});
  fetch("data/search-index.json").then(response=>{if(!response.ok)throw new Error();return response.json();}).then(data=>{entries=data.entries;input.value=new URLSearchParams(location.hash.slice(1)).get("q")||"";render();}).catch(()=>{status.textContent="A busca está indisponível. Use o mapa ou o atlas.";});
})();
