(() => {
  "use strict";
  const list=document.querySelector("#tour-list"),stage=document.querySelector("#tour-stage"),status=document.querySelector("#tour-status");let tours=[],activeTour,stepIndex=0;
  const labels={map:"Abrir no mapa",atlas:"Abrir no atlas",scene3d:"Explorar em 3D"};
  const state=()=>{const params=new URLSearchParams();if(activeTour){params.set("tour",activeTour.id);params.set("step",String(stepIndex+1));}history.replaceState(null,"",params.size?`#${params}`:location.pathname);};
  const button=(label,handler,disabled=false)=>{const node=document.createElement("button");node.type="button";node.textContent=label;node.disabled=disabled;node.addEventListener("click",handler);return node;};
  const renderStep=()=>{const step=activeTour.steps[stepIndex],title=document.createElement("h2"),progress=document.createElement("p"),warning=document.createElement("p"),note=document.createElement("p"),destinations=document.createElement("p"),actions=document.createElement("div");title.textContent=step.title;progress.className="tour-progress";progress.textContent=`Etapa ${stepIndex+1} de ${activeTour.steps.length} · ${activeTour.title}`;warning.className="tour-warning";warning.textContent="Sequência editorial de exploração — não é cronologia nem itinerário canônico.";note.className="tour-note";note.textContent=step.note;destinations.className="tour-destinations";for(const [kind,url] of Object.entries(step.destinations)){const link=document.createElement("a");link.href=url;link.textContent=labels[kind];destinations.append(link);}actions.className="tour-actions";actions.append(button("Etapa anterior",()=>{stepIndex--;renderStep();},stepIndex===0),button("Próxima etapa",()=>{stepIndex++;renderStep();},stepIndex===activeTour.steps.length-1),button("Sair do percurso",clear));stage.replaceChildren(progress,title,warning,note,destinations,actions);list.querySelectorAll("button").forEach(node=>node.setAttribute("aria-pressed",String(node.dataset.tourId===activeTour.id)));state();status.textContent=`${step.title}, etapa ${stepIndex+1} de ${activeTour.steps.length}.`;};
  const select=(tour,index=0)=>{activeTour=tour;stepIndex=Math.max(0,Math.min(tour.steps.length-1,index));renderStep();stage.querySelector("h2")?.focus?.();};
  function clear(){activeTour=undefined;stepIndex=0;const title=document.createElement("h2"),text=document.createElement("p");title.textContent="Escolha um percurso";text.textContent="Você pode começar por qualquer tema e sair a qualquer momento.";stage.replaceChildren(title,text);list.querySelectorAll("button").forEach(node=>node.setAttribute("aria-pressed","false"));state();status.textContent="Percurso encerrado; nenhum progresso foi armazenado.";}
  fetch("data/tours.json").then(response=>{if(!response.ok)throw new Error();return response.json();}).then(data=>{tours=data.tours;list.replaceChildren(...tours.map(tour=>{const node=button(`${tour.title} — ${tour.steps.length} etapas`,()=>select(tour));node.dataset.tourId=tour.id;node.setAttribute("aria-pressed","false");return node;}));const params=new URLSearchParams(location.hash.slice(1)),requested=tours.find(tour=>tour.id===params.get("tour")),requestedStep=Number(params.get("step")||1)-1;if(requested)select(requested,requestedStep);else clear();status.textContent=`${tours.length} percursos editoriais disponíveis.`;}).catch(()=>{stage.innerHTML="<h2>Percursos indisponíveis</h2><p>Use o mapa, o atlas ou a busca pública.</p>";status.textContent="Não foi possível carregar os percursos.";});
})();
