import * as THREE from "./vendor/three.module.min.js";

const canvas=document.querySelector("#scene-canvas"),container=document.querySelector("#scene-container"),status=document.querySelector("#scene-status"),elementList=document.querySelector("#scene-elements"),moduleList=document.querySelector("#scene-modules"),moduleDetail=document.querySelector("#module-detail");
const originLabel={canonical:"Cânone", "cartographic-adaptation":"Adaptação", "visual-reconstruction":"Reconstrução"};
let renderer,scene,camera,theta=.72,phi=.92,radius=34,drag;
const target=new THREE.Vector3(0,0,0),clamp=(value,min,max)=>Math.max(min,Math.min(max,value));

function updateCamera(){camera.position.set(target.x+radius*Math.sin(phi)*Math.cos(theta),target.y+radius*Math.cos(phi),target.z+radius*Math.sin(phi)*Math.sin(theta));camera.lookAt(target);render();}
function render(){renderer.render(scene,camera);window.valgard3dMetrics={...window.valgard3dMetrics,renderCount:(window.valgard3dMetrics?.renderCount||0)+1,drawCalls:renderer.info.render.calls,triangles:renderer.info.render.triangles,geometries:renderer.info.memory.geometries};}
function benchmark(){if(matchMedia("(prefers-reduced-motion: reduce)").matches){window.valgard3dMetrics={...window.valgard3dMetrics,fps:null,reducedMotion:true};return;}let frames=0,start=performance.now();const step=now=>{render();frames++;if(frames<30)requestAnimationFrame(step);else window.valgard3dMetrics={...window.valgard3dMetrics,fps:Math.round(frames/((now-start)/1000)),reducedMotion:false};};requestAnimationFrame(step);}
function material(color,roughness=.85){return new THREE.MeshStandardMaterial({color,roughness});}
function addBox(group,x,z,w,d,h,color){const mesh=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),material(color));mesh.position.set(x,h/2,z);group.add(mesh);return mesh;}
function createTerrain(){const geometry=new THREE.PlaneGeometry(42,34,32,26);geometry.rotateX(-Math.PI/2);const positions=geometry.attributes.position;for(let i=0;i<positions.count;i++){const x=positions.getX(i),z=positions.getZ(i);const rim=.014*(x*x+z*z),valley=-1.15*Math.exp(-(z*z)/22)*Math.exp(-(x*x)/180),variation=.22*Math.sin(x*.38)*Math.cos(z*.31);positions.setY(i,rim+valley+variation);}geometry.computeVertexNormals();const mesh=new THREE.Mesh(geometry,material(0x668455));mesh.receiveShadow=true;scene.add(mesh);}
function createRiver(){const curve=new THREE.CatmullRomCurve3([new THREE.Vector3(-21,.05,-6),new THREE.Vector3(-11,-.45,-3),new THREE.Vector3(0,-.75,0),new THREE.Vector3(11,-.42,2),new THREE.Vector3(21,.1,5)]);const mesh=new THREE.Mesh(new THREE.TubeGeometry(curve,40,.72,6,false),new THREE.MeshStandardMaterial({color:0x3e84a8,roughness:.3,metalness:.05}));scene.add(mesh);}
function createFields(){const geometry=new THREE.BoxGeometry(3.4,.08,2.4),mesh=new THREE.InstancedMesh(geometry,material(0xa89554),15),dummy=new THREE.Object3D();let index=0;for(let row=0;row<3;row++)for(let col=0;col<5;col++){dummy.position.set(-13+col*4.1,.04,5+row*3.1);dummy.rotation.y=col%2?-.08:.08;dummy.updateMatrix();mesh.setMatrixAt(index++,dummy.matrix);}scene.add(mesh);}
function createRoads(){const paths=[[[0,0],[18,-10]],[[0,0],[17,11]],[[0,0],[-18,10]],[[0,0],[-19,-9]]],points=paths.flatMap(path=>path.map(([x,z])=>new THREE.Vector3(x,.16,z)));scene.add(new THREE.LineSegments(new THREE.BufferGeometry().setFromPoints(points),new THREE.LineBasicMaterial({color:0x9c835d})));}
function createSettlement(){const positions=[[-3,-3],[-1,-4],[1,-3],[3,-2],[-4,-.7],[-2,-1],[1,-.5],[3,.5],[-3,2],[-.5,2.5],[2.2,2.7],[4,2]],geometry=new THREE.BoxGeometry(1.25,1,.9),houses=new THREE.InstancedMesh(geometry,material(0x8a6a47),positions.length),dummy=new THREE.Object3D();for(let i=0;i<positions.length;i++){const [x,z]=positions[i],height=.7+(i%3)*.15;dummy.position.set(x,height/2,z);dummy.scale.set(1,height,1);dummy.rotation.y=(i%4)*.22;dummy.updateMatrix();houses.setMatrixAt(i,dummy.matrix);}scene.add(houses);const hall=new THREE.Group();addBox(hall,0,0,2.2,1.8,1.45,0x665344);scene.add(hall);}
function createUrbanDetails(){const square=new THREE.Mesh(new THREE.CylinderGeometry(2.2,2.2,.08,20),material(0xb69b73));square.position.y=.11;scene.add(square);const barn=new THREE.Group();addBox(barn,-5,4,2.4,1.5,1.2,0x765438);scene.add(barn);const posts=new THREE.InstancedMesh(new THREE.CylinderGeometry(.12,.16,1.6,6),material(0x5e4936),6),dummy=new THREE.Object3D();for(let i=0;i<6;i++){dummy.position.set(4.2+i*.55,.8,-3.2+Math.sin(i)*.2);dummy.updateMatrix();posts.setMatrixAt(i,dummy.matrix);}scene.add(posts);createLandscape();}
function createLandscape(){const vegetation=new THREE.InstancedMesh(new THREE.ConeGeometry(.45,1.7,6),material(0x3f693d),36),dummy=new THREE.Object3D();vegetation.name="landscape-vegetation";for(let i=0;i<36;i++){const side=i%2?-1:1,x=side*(9+(i%9)*1.25),z=-13+Math.floor(i/9)*8+(i%3)*.45;dummy.position.set(x,.85,z);dummy.scale.setScalar(.75+(i%4)*.09);dummy.updateMatrix();vegetation.setMatrixAt(i,dummy.matrix);}scene.add(vegetation);const bankPoints=[],course=[[-21,-6],[-11,-3],[0,0],[11,2],[21,5]];for(const offset of [-1,1])for(let i=0;i<course.length-1;i++){const [x1,z1]=course[i],[x2,z2]=course[i+1];bankPoints.push(new THREE.Vector3(x1,.2,z1+offset),new THREE.Vector3(x2,.2,z2+offset));}const banks=new THREE.LineSegments(new THREE.BufferGeometry().setFromPoints(bankPoints),new THREE.LineBasicMaterial({color:0x7b9a68}));banks.name="landscape-riverbanks";scene.add(banks);const markerPositions=[[14,-8],[13,9],[-14,8],[-15,-7]],markers=new THREE.InstancedMesh(new THREE.ConeGeometry(.38,1.5,5),material(0xd9bd78),4);markers.name="landscape-route-markers";for(let i=0;i<markerPositions.length;i++){const [x,z]=markerPositions[i];dummy.position.set(x,.75,z);dummy.scale.set(1,1,1);dummy.updateMatrix();markers.setMatrixAt(i,dummy.matrix);}scene.add(markers);}
function bindControls(){const rotate=amount=>{theta+=amount;updateCamera();},zoom=factor=>{radius=clamp(radius*factor,14,55);updateCamera();};container.addEventListener("pointerdown",event=>{drag={x:event.clientX,y:event.clientY,theta,phi};container.setPointerCapture(event.pointerId);});container.addEventListener("pointermove",event=>{if(!drag)return;theta=drag.theta-(event.clientX-drag.x)*.008;phi=clamp(drag.phi+(event.clientY-drag.y)*.006,.35,1.38);updateCamera();});container.addEventListener("pointerup",()=>{drag=undefined;});container.addEventListener("wheel",event=>{event.preventDefault();zoom(event.deltaY<0?.9:1.1);},{passive:false});container.addEventListener("keydown",event=>{const actions={ArrowLeft:()=>rotate(-.12),ArrowRight:()=>rotate(.12),ArrowUp:()=>{phi=clamp(phi-.08,.35,1.38);updateCamera();},ArrowDown:()=>{phi=clamp(phi+.08,.35,1.38);updateCamera();},"+":()=>zoom(.9),"-":()=>zoom(1.1),"0":reset};if(actions[event.key]){event.preventDefault();actions[event.key]();}});document.querySelector("#scene-left").onclick=()=>rotate(-.15);document.querySelector("#scene-right").onclick=()=>rotate(.15);document.querySelector("#scene-in").onclick=()=>zoom(.88);document.querySelector("#scene-out").onclick=()=>zoom(1.12);document.querySelector("#scene-reset").onclick=reset;document.querySelectorAll("[data-scene-layer]").forEach(input=>input.addEventListener("change",()=>{const object=scene.getObjectByName(`landscape-${input.dataset.sceneLayer}`);if(object)object.visible=input.checked;render();status.textContent=`Camada ${input.parentElement.textContent.trim()} ${input.checked?"visível":"oculta"}.`;}));}
function reset(){theta=.72;phi=.92;radius=34;target.set(0,0,0);updateCamera();}
function resize(){const width=container.clientWidth,height=container.clientHeight;renderer.setPixelRatio(1);renderer.setSize(width,height,false);camera.aspect=width/height;camera.updateProjectionMatrix();render();}
function populateModules(modules){const select=item=>{const button=moduleList.querySelector(`[data-module-id="${item.id}"]`);moduleList.querySelectorAll("button").forEach(node=>node.setAttribute("aria-pressed","false"));button?.setAttribute("aria-pressed","true");target.set(item.position[0],0,item.position[1]);radius=22;updateCamera();moduleDetail.textContent=`${item.name}: ${item.description} Origem: reconstrução visual.`;status.textContent=`${item.name} selecionado. Este módulo não é cânone.`;const params=new URLSearchParams(location.hash.slice(1));params.set("module",item.id);history.replaceState(null,"",`#${params}`);};moduleList.replaceChildren(...modules.map(item=>{const button=document.createElement("button");button.type="button";button.textContent=item.name;button.dataset.moduleId=item.id;button.setAttribute("aria-pressed","false");button.addEventListener("click",()=>select(item));return button;}));const requested=new URLSearchParams(location.hash.slice(1)).get("module"),item=modules.find(candidate=>candidate.id===requested);if(item)requestAnimationFrame(()=>select(item));}
async function initialize(){const response=await fetch("data/valgard-3d.json");if(!response.ok)throw new Error("contrato da cena indisponível");const config=await response.json();elementList.replaceChildren(...config.elements.map(item=>{const li=document.createElement("li");li.textContent=`${item.name} — ${originLabel[item.visualOrigin]}`;li.title=item.description;return li;}));populateModules(config.modules);const gl=canvas.getContext("webgl2",{antialias:false,powerPreference:"low-power"});if(!gl)throw new Error("WebGL 2 indisponível; use o mapa 2D");renderer=new THREE.WebGLRenderer({canvas,context:gl,antialias:false,powerPreference:"low-power"});scene=new THREE.Scene();scene.background=new THREE.Color(0x9ec5d8);camera=new THREE.PerspectiveCamera(48,1,.1,120);scene.add(new THREE.HemisphereLight(0xe8f2ff,0x4c432e,2.1));const sun=new THREE.DirectionalLight(0xffe7bd,2.2);sun.position.set(-12,24,-8);scene.add(sun);createTerrain();createRiver();createFields();createRoads();createSettlement();createUrbanDetails();bindControls();new ResizeObserver(resize).observe(container);resize();reset();benchmark();status.textContent=`Cena experimental carregada: ${config.elements.length} grupos e ${config.modules.length} módulos, alturas apenas visuais.`;}
initialize().catch(error=>{status.textContent=`Protótipo 3D indisponível: ${error.message}. O mapa 2D permanece acessível.`;canvas.hidden=true;});
